provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  ENTraslator:
    lang: go
    handler: ./ENTranslator
    image: s8sg/entranslator
    environment:
      APIKEY: AIzaSyBO3AbUrJngcM8ZTpg0GMPe8VHibv4pH-4 
